
NAME    =   colle-2

SRCS    =   print.c  read.c check.c check_2.c ass.c 

LIB     =   includes/header.h

all     :   $(NAME)

$(NAME) :
	gcc -o $(NAME) -Wall -Werror -Wextra $(SRCS) -I $(LIB)

fclean: 
	/bin/rm -f $(NAME)
