#!/bin/bash
cat <<EOT >> hello.py
from flask import Flask
app = Flask(__name__)
 
@app.route("/")
def hello():
    return "<h1>Hello World!</h1>"
 
if __name__ == "__main__":
    app.run()
EOT

docker-machine ssh Char mkdir /home/lkaba
docker-machine scp hello.py Char:/home/lkaba
docker run -d --name Abathur -v /home/lkaba:/root --env FLASK_APP=hello.py -w /root -p 3000:3000 python:2-slim bash -c 'pip install flask && flask run -h 0.0.0.0 -p 3000'