#!/bin/bash
docker service create \
--detach \
--network overmind \
--hostname orbital-command \
--name orbital-command \
--env RABBITMQ_DEFAULT_USER="lkaba" \
--env RABBITMQ_DEFAULT_PASS="lkaba" \
rabbitmq